### ISSUE TITLE
Migration from 0.4.0 to 1.1.0 fails because of the <span> tag in 1.1.0

### ISSUE THREAD

**Issue by wingedfox** [rubenv/angular-gettext#101]
Hi,

Is there an easy way to migrate from 0.4.0 to 1.1.0?
As long as 1.1.0 starts to add <span> with translated string, it fails in certail scenarios like

``` html
  <option translate>default</option>
```

which ends up with

``` html
  <option translate>
    <span class="ng-scope">Default value</span>
  </option>
```

**Comment by circlingthesun** [comment]
Angular 1.6 fixes the span issue. See:
Spans in 1.5.9: http://plnkr.co/edit/tKloB8LFk3GCAsu0UEUx?p=preview
No spans in 1.6.0: http://plnkr.co/edit/tE96QrOPtqxuxR4xbxRL?p=preview

**Comment by wingedfox** [comment]
Great to see this fixed =)
