### ISSUE TITLE
Both translations displayed

### ISSUE THREAD

**Issue by chOse** [rubenv/angular-gettext#124]
Hello,

I'm using this with an Ionic / Angular / Cordova app and it does the job quite successfully.
I only have a problem that occurs sometimes when running the app on a phone (Android or iOS, no problem with the browser version) translated texts appear in both versions : Text_FR:Text_EN, instead of the appropriate one.
I would expect that even if the correct locale was not detected, it would display the default language (ie english)
Any idea why this would happen ?

For information, in my index.html in run js files in this order : 
- Ionic + Angular JS
- Angular gettext + other libraries
- Translations JS file
- Angular's app.js (locale detection is made here, in the angular.run command)

Thank you very much

**Comment by carlosgalindo** [comment]
Please see my comment @ https://github.com/rubenv/angular-gettext/issues/161#issuecomment-87016083
