### ISSUE TITLE
translate is an HTML5 attribute

### ISSUE THREAD

**Issue by Toilal** [rubenv/angular-gettext#153]
I was reviewing angular-translate issues and find this one that angular-gettext shares : https://github.com/angular-translate/angular-translate/issues/849

To make it short, translate is now an [HTML5 attribute](http://www.w3.org/International/questions/qa-translate-flag), so this directive should be renamed to something else. Or maybe it could be kept and match the attribute specs.

**Comment by gabegorelick** [comment]
Please correct me if I'm wrong, but it looks like the HTML5 translate
attribute just provides metadata to external translation services like
Google translate, so I don't think it's a huge conflict. In fact, I think
that might work well with this directive. If you're concerned, you can use
data-translate instead.

That being said, it might be useful for us to support translate="yes" and
translate="no" for compatibility with the spec.

**Comment by Toilal** [comment]
I'm not sure it's consistent to try to follow the spec.

Main strange thing is that default is translate="yes" set on root element ... This would make angular-translate automatically extract and translate everything ?

I don't really know what the best to do, maybe nothing and stick with this actual simple and readable "translate" directive unless real world problems arise ...

**Comment by rubenv** [comment]
That's usually what I do in cases like this: ignore the problem until it
actually exists.

But it's very good to be aware of it. I didn't knew this existed, so I'm
happy that you mention it.

I see this potentially going in two directions:
- stuff keeps working and we don't have to do anything
- things break horribly and we're forced to act.

I wouldn't lose any sleep over it until scenario 2 kicks in :-)

**Comment by Toilal** [comment]
Totally agree :) I close this one, hope it won't appear later !
