### ISSUE TITLE
First class i18n support is in the pipeline for Angular 1.4

### ISSUE THREAD

**Issue by circlingthesun** [rubenv/angular-gettext#155]
@rubenv it may be worth joining the discussion at https://docs.google.com/document/d/1mwyOFsAD-bPoXTk3Hthq0CAcGXCUw-BtTJMR4nGTY-0/edit#

**Comment by rubenv** [comment]
Am keeping an eye on it, but it's currently release crunch, so I really don't have time for it.

I'm trusting that you spread some of our ideas there :-)

**Comment by gabegorelick** [comment]
Looks like they'll support xgettext-style extraction, so I have no complaints. I honestly have no idea how people can stand to manually maintain their message bundles :)

**Comment by rubenv** [comment]
If that's the case: our work is done :-)

My number 1 motivation for building angular-gettext was that localising with message identifiers is idiotic.
