### ISSUE TITLE
how to extract same word twice, where we have 2 different meanings?

### ISSUE THREAD

**Issue by NVK15** [rubenv/angular-gettext#156]
Hi,

I am trying to translate my english strings to German. I have a requirement where the same english text might have different meanings and need to provide two different german word translations in two different pages for the same english text.
I tried adding different translate-comment to the same text, but it would appear only once in POT File when extracted. Is there a way to handle it?

Thanks.

**Comment by gabegorelick** [comment]
You want contexts: https://www.gnu.org/software/gettext/manual/html_node/Contexts.html

This is supported in angular-gettext, but not documented yet (see https://github.com/rubenv/angular-gettext-website/issues/4).

**Comment by NVK15** [comment]
Thanks for the reply, but how would we use it?

**Comment by gabegorelick** [comment]
If you're using the `translate` directive, which you should try to use whenever possible, it's pretty easy:
```html
<span translate translate-context="female">Hello</span>
```

**Comment by NVK15** [comment]
How would i add translation context for text in javascript file which has to be translated?
