### ISSUE TITLE
how to merge or update existing po files

### ISSUE THREAD

**Issue by shaurabh-singh** [rubenv/angular-gettext#157]
Hi,
We are using gettext in our application, it is still in development phase. And after every build we need to  include the new strings in the existing po file. Is there any way to do this or can we merge the existing po files ?

**Comment by intellix** [comment]
We're using an online tool called Pootle, which looks like the following: http://pootle.locamotion.org/

You basically upload your POT then in the admin, have your languages updated against it. If you're after something smaller scale though, we also used Poedit where you can Merge from a POT file generated by this project.

**Comment by shaurabh-singh** [comment]
@intellix thank you for the reply. 
but still I am not clear on how Poedit can be used for merging PO/POT files, can you explain how this can be done?

**Comment by rubenv** [comment]
@shaurabh-singh It's described on the bottom of this page: https://angular-gettext.rocketeer.be/dev-guide/translate/#afterwards

**Comment by gabegorelick** [comment]
@shaurabh-singh I'm closing this issue since it doesn't appear to be a bug. But feel free to continue to post questions in this thread, or open a new one. Thanks.
