### ISSUE TITLE
setCurrentLanguage concatenates, instead of replacing

### ISSUE THREAD

**Issue by morfin** [rubenv/angular-gettext#161]
Hi,

When I want to change language and run setCurrentLanguage() on runtime, instead of replacing strings, it just concatenates new language. 

What's the proper way to update language on the fly ?

Thanks.

**Comment by rubenv** [comment]
I have no idea what you mean with concatenate, it should just set the new language:
https://github.com/rubenv/angular-gettext/blob/7f5fd0ab1b8aaac626aefd7bef44fbd1249f6af8/src/catalog.js#L43-L46

Do you have an example of what you are seeing?

**Comment by gabegorelick** [comment]
@morfin Feel free to keep commenting on this issue, but I'm closing it for now.

**Comment by morfin** [comment]
What I mean is that it ends up showing both languages, one string next to the other.

For instance, if current language is english, the word "Nothing" is shown. If I set spanish, it shows: "NothingNada"

That happens to all the words.

**Comment by rubenv** [comment]
Have you tried wrapping the call in
```js
$scope.$apply(function () {
   // code here
}):
```
?

Setting the language needs to happen in the digest loop.

**Comment by carlosgalindo** [comment]
If I include "element.empty();" before $animate.enter (and even remove $animate.leave) in angular-gettext.js, all the duplicate problems seem to go away.

Is it possible to include this (or similar) fix in your great project?.

Thanks.

**Comment by rubenv** [comment]
@carlosgalindo That completely breaks ngAnimate, so no that's not an option.

**Comment by carlosgalindo** [comment]
Hi, that's what I mean about using a "similar" fix, one that somehow ensures the parent element is empty before the "enter" event, and/or that "newContents" is the only element child after the $animate enter/leave calls. The duplicate issues occur not only when switching languages, but also when loading/updating async sections. Thanks!

**Comment by rubenv** [comment]
@carlosgalindo emptying the parent first is exactly what would break animation support, so we're definitely not going to do that. Now, chances are high that this is an easy-to-fix bug in your project.

The only way for us to help fix this is if you can provide us with a piece of sample code that shows the bug. Please make an example on [http://jsfiddle.net/](http://jsfiddle.net/) that demonstrates the problem.

**Comment by ThomasHambach** [comment]
I am having the same issue. I tried the $apply, but that has no effect. I assume it is something with the animate callback.

Quick fix was forking and removing the animate statements. Will do some more digging into what is causing the issue at a later time.

    //var oldContents = element.contents();
    var newContents = newWrapper.contents();
    element.empty().html(newContents.html());
    // $animate.enter(newContents, element);
    // $animate.leave(oldContents);

**Comment by manuelmazzuola** [comment]
@ThomasHambach Thanks

**Comment by circlingthesun** [comment]
Could those of you experiencing this issue check if #187 resolves it.

**Comment by rubenv** [comment]
This should be fixed by `v2.1.0`. Please test it. If it doesn't work: let us know.
