### ISSUE TITLE
Bug; translate in conjunction with ng-repeat

### ISSUE THREAD

**Issue by pere5** [rubenv/angular-gettext#162]
We have this:

js:
```javascript
$scope.categories = [
            'Art',
            'Automotive',
            'Bookstore',
            'Clothing',
            ...
        ];
```
HTML:
```HTML
            <select ng-model="category" >
                <option value="" translate="">search.bar.Category</option>
                <option value="{{category}}" ng-repeat="category in categories" translate="">{{'category.' + category | translate}}</option>
            </select>
```
Textkeys file that allows angular-gettext to find the textkeys:
```HTML
            <span translate="">category.Art</span>
            <span translate="">category.Automotive</span>
            <span translate="">category.Bookstore</span>
            <span translate="">category.Clothing</span>
            ...
```

The result is that the translation works fine in the dropdown, BUT when changing language and having `gettextCatalog.debug = true;` each successfully translated string gets the [MISSING] - prefix.

So as I said, the translation works but the system adds [MISSING] anyway.

**Comment by rubenv** [comment]
That's really not how you want to be working.

For starters, you're randomly sprinking `translate=""` and `ng-options=""`, everywhere, which is a recipe for things not working as you expect (especially that `ng-options` one, that's going to give you headaches if you don't know what it does).

Here's what you probably want to be doing:

```js
        $scope.categories = [
            gettext('Art'),
            gettext('Automotive'),
            gettext('Bookstore'),
            gettext('Clothing'),
            ...
        ];
```

```html
            <select ng-model="category">
                <option value="" translate>Pick a category</option>
                <option value="{{category}}" ng-repeat="category in categories">{{category | translate}}</option>
            </select>
```

Or better:

```js
$rootScope.translate = gettextCatalog.getString;
```

```html
<select ng-model="category" ng-options="cat as translate(cat) for cat in categories" />
```

Any kind of nonsense where you're mapping symbolic strings to translations is just plain wrong, don't do it.

**Comment by pere5** [comment]
@rubenv Thank you. I went for the first solution. The latter seemed more elegant but `$rootScope.translate = gettextCatalog.getString;` didn't work. The function getString was unable to operate when not called directly in gettextCatalog and the result was a:
```
Uncaught TypeError: undefined is not a functionangular-gettext.min.js:1 g.getStringrun.js:12 (anonymous function)angular.js:4138 invokeangular.js:3960 (anonymous function)angular.js:322 forEachangular.js:3960 createInjectorangular.js:1434 doBootstrapangular.js:1455 bootstrapangular.js:1349 angularInitangular.js:25912 (anonymous function)jquery.js:3048 jQuery.Callbacks.firejquery.js:3160 jQuery.Callbacks.self.fireWithjquery.js:433 jQuery.extend.readyjquery.js:104 completed
```

Closing ticket. Thank you!

**Comment by pere5** [comment]
@rubenv Actually, I found the issue and I'm sorry to have brought it up here. This was the original code I used:

```
<select class="form-control" ng-model="category" >
        <option value="" translate="">search.bar.Category</option>
        <option value="{{category}}" ng-repeat="category in categories" translate="">{{'category.' + category | translate}}</option>
</select>
```

As you can see I accidentally left a `translate=""` AND a `| translate` on the same translation!

Thanks again and sorry for bothering you!
