### ISSUE TITLE
Parse external files to extract translated keys

### ISSUE THREAD

**Issue by AlexCapi** [rubenv/angular-gettext#164]
Hi,

Is it possible with the grunt task ```nggettext_extract``` to parse external files, something like a public directory on another URI? I tried this but it did not work : 
````
nggettext_extract: {
            pot: {
                files: {
                    'po/accred-front.pot': ['http://external-url.com/views/{,*/}*.html', '<%= yeoman.app %>/scripts/{,*/}*.js']
                }
            }
        },
````

**Comment by circlingthesun** [comment]
Find a way of downloading the files you need via some grunt plugin (maybe https://github.com/twolfson/grunt-curl) and then point angular-gettext to where you placed them.

**Comment by AlexCapi** [comment]
Thank you for that solution ! I am giving it a try but it should be fine

**Comment by AlexCapi** [comment]
It seems something goes wrong with grunt-curl. I installed it via npm, but when I configure it like this : 
````
'curl-dir': {
            '<%= yeoman.app %>/views': [
                '<%= yeoman.accred %>/views'
            ]
        },
````
I have the error ```Warning: Task "curl-dir" not found.```. And when I remove the quotes I got syntax error because it seems you can just use CamelCase or underscores to name tasks ..
