### ISSUE TITLE
[Question] Default language without translation file

### ISSUE THREAD

**Issue by skosno** [rubenv/angular-gettext#165]
Hi,

Our default template language is English and it feels troublesome to have translation from EN to EN (it might be needed for some installation that wishes to change default translations). Any way to inform gettext about default translation language so that it does not attempts to find translation?

Or in such case you would just turn off debug and that's it?

**Comment by rubenv** [comment]
Just turn debug of. We have a project where we do exactly that: allow customisation of user interface strings by allowing users to edit the English texts. For 99% of the strings the translation is empty, so it falls back to the default string.

**Comment by skosno** [comment]
Thanks for comment.
