### ISSUE TITLE
Interpolation?

### ISSUE THREAD

**Issue by michelem09** [rubenv/angular-gettext#167]
Hello,
I cannot understand what's wrong here, I have this sentence:

    <p translate>Hello <strong>{{userData.name}}</strong></p>

On my Po editor I translated it as:

    Ciao <strong>{{userData.name}}</strong>

Now, on frontend I only got:

    Ciao <strong></strong>

What's wrong?

**Comment by rubenv** [comment]
Do you have a jsFiddle example of the code you are using?

Which browser are you using?

**Comment by michelem09** [comment]
I could try to replicate it in a fiddle. I'm trying with latest Firefox.

**Comment by michelem09** [comment]
Sorry my bad! Wrong scope name...
