### ISSUE TITLE
setCurrentLanguage in 2.0.4 is broken.

### ISSUE THREAD

**Issue by PSyton** [rubenv/angular-gettext#171]
Now it isn't possible to call setCurrentLanguage inside $apply:

for eaxample:

    $http(...).then(function() {
       ...
      gettextCatalog.setCurrentLanguage(someId);
      ...
    })...

**Comment by rubenv** [comment]
Oh crap, that's why we didn't do that. Will revert.

**Comment by rubenv** [comment]
Released `2.0.5`. Sorry for that!
