### ISSUE TITLE
Adding msgmerge support

### ISSUE THREAD

**Issue by worldspawn** [rubenv/angular-gettext#174]
Hi, I've been trying to find a way to add support for msgmerge and failing that something like what msgmerge does. The idea is to push new translation entries into the PO files (from the POT file).

I've written some scrappy code to do this with gulp and `pofile` but I struggle with all these promises :)

The below code obviously doesnt wait properly and the promise returned is never resolved but it is working ok as a self run dev task. I thought might provide some inspiration to add support for this to angular-gettext. 

It could probably compare references where it finds a matching msgid and add missing references to the po file entry as well.

```
gulp.task('mergepot', function() {
  var deferred = Q.defer();
  Po.load(__dirname + '/../po/template.pot', function (err, pot) {
    if (err){
      console.log(err);
      deferred.reject(err);
      return;
    }

    gulp.src('po/**/*.po')
      .pipe($.foreach(function(stream, file) {
        console.log(file.path);
        Po.load(file.path, function (err, po) {
          if (err){
            console.log(err);
            deferred.reject(err);
            return;
          }

          var changed = false;
          pot.items.forEach(function(potItem) {
            var found = false;
            po.items.forEach(function (poItem) {
              //console.log(poItem.msgid, potItem.msgid)
              if (poItem.msgid === potItem.msgid) {
                found = true;
              }
            });

            if (!found){
              console.log('not found', potItem.msgid)
              po.items.push(potItem);
              changed = true;
            }
          });

          if (changed) {
             po.save(file.path, function (err) {
            //
             });
          }

          //console.log(po.items);
        });
      }))
      .pipe($.size());
  });

  return deferred.promise;
});
```

**Comment by gabegorelick** [comment]
Cool, but why can't you just use the GNU msgmerge program directly? Or is
this an exercise in implementing msgmerge in JS?

**Comment by worldspawn** [comment]
I work on a windows platform and theres no windows package manager i can reliably install msgmerge with.  IMHO its a gap in the angular-gettext offering. We have extract and compile but every time I do an extract I also want my po files to be updated.

**Comment by gabegorelick** [comment]
A cursory search turns up a few Windows gettext resources, and of course
there's always Cygwin. But anyway, this is outside the scope of
angular-gettext. We support going from Angular to PO and from PO to
Angular, but msgmerge is about going from PO to PO. It's certainly an
important part of the gettext workflow (although nowadays most translation
happens on online platforms  or other tools where this merging happens
without the need to directly run msgmerge). But it has nothing to do with
Angular, as it's a general tool for working with PO files.

See https://github.com/praekelt/jspot/issues/12 for some people outside
this project that also wanted a JS msgmerge.

**Comment by worldspawn** [comment]
Indeed. I've used gettext based tech in one project years ago and I am just rediscovering it. I was looking at the angular-translate package but I remembered the po based system was far better. Tooling wise, I found the google translator toolkit was pretty good but its a rather manual workflow. Poedit requires me to run 'Update from Catalog' manually for each po file so that didn't cut the mustard.

The important thing of me was to get blank entries injected into the po file using the pot as a source of truth. I'll keep working on this code but it's unlikely to ever do everything that msgmerge does.  Perhaps, if I can get it to reasonable quality, you could include it here in the wiki or something to help others out?

**Comment by gabegorelick** [comment]
Happy to link to anything in the README :-)

Also, you may want to check out transifex or a similar web-based
localization product. They complement the gettext workflow nicely.

**Comment by worldspawn** [comment]
Ok link away - https://gist.github.com/worldspawn/720b83a034d613571111

That includes a merge function without any gulp dependency and a gulp function to wrap the merge and a usage example. I am 99% sure all the promises are waiting properly.

According to msgmerge (https://www.gnu.org/software/gettext/manual/html_node/msgmerge-Invocation.html) when it finds a match 
> comments will be preserved, but extracted comments and file positions will be discarded

So I've implemented that. I'm not clear on what happens to entries in the po file that arnt in the pot file, I'm assuming they are left alone.

It doesn't do any kind of fuzzy matching, ids must match exactly.
