### ISSUE TITLE
it can't extract .tmpl file

### ISSUE THREAD

**Issue by joebnb** [rubenv/angular-gettext#175]
```
		nggettext_extract:{
			pot:{
				options:{
					startDelim:'##',
					endDelim:'##'
				},
				files:{
					'./lang/language.pot':['<%= config.src %>/web/**/*.html','<%= config.src %>/web/**/*.tmpl']
				}
			}
		},
```
i rename all template file in project with .tmpl,it can't trim it

**Comment by rubenv** [comment]
You'll need to use the `extensions` option to map `.tmpl` files to `html`: https://github.com/rubenv/angular-gettext-tools/blob/a509df9d0d5d1c6ce4975d5f80b950cc95075463/lib/extract.js#L70-L79

**Comment by rubenv** [comment]
Note that we can add it by default, but to do that, we need a sample file + unit test. Pull request in https://github.com/rubenv/angular-gettext-tools welcome!

**Comment by joebnb** [comment]
so fast!with great thanks

**Comment by joebnb** [comment]
and sorry...i dont konw how to write a unit test now

**Comment by gabegorelick** [comment]
Closing this since it seems like you solved your issue.
