### ISSUE TITLE
new problem about js file

### ISSUE THREAD

**Issue by joebnb** [rubenv/angular-gettext#176]
i want translate string in javascript file with angular-gettext ,how to do it work?
```
	notifyService.make=function(type,msg,time){
		$rootScope.notify.push({
			'status':true,
			'type':type,
			'msg':msg
		})
		if(time != '' && !isNaN(time)){
			$timeout(function(){
				//pop array,so it happen to ng-repeat will decrease 1
				var index
				$rootScope.notify.splice(index, 1);
			},time*1000)
		}
	},
```
i wrote a service with root scope,gettext can translate some string in scope ？
and this service work with a directive

**Comment by rubenv** [comment]
All you need should be in the developer guide: https://angular-gettext.rocketeer.be/dev-guide/
