### ISSUE TITLE
multiple translation files?

### ISSUE THREAD

**Issue by enapupe** [rubenv/angular-gettext#177]
Is there any way to split translation files?
Suppose I have two modules on my app, one is shared between other apps and one is specific to the current app. Regarding cache and bandwidth optimization, it would be nice if I could load two files: `shared/en.json` and `appspecific/en.json`, so, when the user loaded a second app, the `shared/en.json` would already be cached..
Otherwise I'm gonna have to concatenate all specific app files with shared OR generate one big file with all lines from all apps plus shared..
Thanks

**Comment by enapupe** [comment]
Well.. going a little bit further on my question, actually I could do myself the requests, concat the objects and feed angular-gettext..

**Comment by gabegorelick** [comment]
Take a look at the [discussion about domains](https://github.com/rubenv/angular-gettext/issues/95).

**Comment by enapupe** [comment]
Ok thks.
