### ISSUE TITLE
directive 'translate' broken in angular 1.4.0-rc0. No element.parent()

### ISSUE THREAD

**Issue by reifi** [rubenv/angular-gettext#179]
Probably because of $animate breaking changes in angular 1.4.0-rc0

```javascript
<span translate>translation_key_will_break</span>

<span>{{'translation_key_works'|translate}}</span>
```

Angular Error: element.parent is not a function

angular-gettext.js line 197,198: 
https://github.com/rubenv/angular-gettext/blob/master/dist/angular-gettext.js#L197
```javascript
                        $animate.enter(newContents, element);
                        $animate.leave(oldContents);
```

**Comment by circlingthesun** [comment]
I've noticed this, had a look and could not determine exactly why this happening. It may be worth waiting for rc1 to see if this is an angular bug.

**Comment by reifi** [comment]
Quickfix: 

replace line 197 and 198 with:

```javascript
oldContents.replaceWith(newContents);
```

I wouldnn't use $animate at all

**Comment by crisbeto** [comment]
The animate API was changed in 1.4, it looks like its this line that is causing the problem https://github.com/rubenv/angular-gettext/blob/master/dist/angular-gettext.js#L198. I'll play around with it to see if I can fix this.

**Comment by circlingthesun** [comment]
Still broken in rc-1

**Comment by circlingthesun** [comment]
It appears to only break when swapping out text nodes.

**Comment by crisbeto** [comment]
Yeah, a method in ngAnimate returns `false` instead of an element which causes the error. I've posted an issue: https://github.com/angular/angular.js/issues/11703

**Comment by circlingthesun** [comment]
I cannot reproduce this in isolation. I had a stab at it here: https://jsfiddle.net/xtnhqstp/10/. If anyone can help be reproduce the bug, that would be great. It would give your bug report more weight.

**Comment by crisbeto** [comment]
@circlingthesun You need to include `ngAnimate` in your app. Here's a forked version with the problem  https://jsfiddle.net/pLvmf9qg/

**Comment by circlingthesun** [comment]
Doh! I forgot that including the file is not enough. You should add that to your bug.

**Comment by circlingthesun** [comment]
It appears that the ng-animate refactor does not currently support animation of text nodes. When ```element.contents()``` returns a text node instead of an element, ```$animate.leave()``` fails. I'm not sure if this was a design choice or an oversight. No one from the angular team has commented on this yet.

**Comment by crisbeto** [comment]
Well it fails because that comment-stripping function fails. The error is that it can't run `parent` on `false` which gets returned from `element[0].nodeType === ELEMENT_NODE && element`. 
I also took at your PR, I tried something similar yesterday and it worked the first time, but if you try to switch languages there was always 1 TextNode that wouldn't get removed.

**Comment by circlingthesun** [comment]
Well, its not only the comment stripping function that's assuming element nodes. So that's why the text nodes are not being removed.

**Comment by circlingthesun** [comment]
@crisbeto, I think the one text node not being removed may be related to #161. I submitted #187 that seems to resolve this issue after applying https://github.com/angular/angular.js/pull/11722.

**Comment by crisbeto** [comment]
Yeah those two fixes definitely work. Great job, this was a pretty convoluted issue. 
A quick question: Isn't `oldContents[0].textContent` the same as `oldContents.text()` or `oldContents.html()` (not sure if `html` works on text nodes) [here](https://github.com/circlingthesun/angular-gettext/blob/fix-double-text/src/directive.js#L63)?

**Comment by circlingthesun** [comment]
@crisbeto, good spot. JQuery or JqLite wrappers can contain multiple top level nodes. The ```.text()``` and ```.html()``` functions concatenates the result after stringifying all the elements. ```oldContents[0].textContent``` unwraps only the first element and gets the text with html tags stripped out. What I should have done is use ```oldContents.html()``` as it is what what angular-gettext-tools uses to extract strings.

**Comment by crisbeto** [comment]
One thing to keep in mind though: This module has problems with multi-line strings exactly because it uses `.html()` to extract and compare the strings. Sometimes the result from the extract tool and the ones from the directive can be different, which why I had to write my own patches for it.

**Comment by rubenv** [comment]
> which why I had to write my own patches for it.

Have these patches been upstreamed?

**Comment by crisbeto** [comment]
No, they haven't. I consider them a bit hacky and they work for my specific usecase. If you want to take a look, here are a couple of gists.

[Grunt task](https://gist.github.com/crisbeto/4e41322dc85cbec0c1cc). It runs after the compile task and checks for "risky" characters. These are usually html, \r, \n and &. It escapes the ampersand and if it detects any of the others, it makes a fallback version of the key that doesn't have html, newlines or whitespace.
Afterwards the [client-side patch](https://gist.github.com/crisbeto/da13aaa51b5f20e67851) tries to find the literal key name. If it can't, it removes all the html, whitespace and newlines.
I think this could be a slow on the client side since it involves matching regexps and replacing strings. For me it wasn't much of a problem since these cases are only about 5% of total translations.

**Comment by rubenv** [comment]
This should be fixed by `v2.1.0`. Please test it. If it doesn't work: let us know.

**Comment by crisbeto** [comment]
It looks like most cases are fixed, however it still has the problem with the strings being double, if there's interpolation inside the directive, e.g. `<span translate>Hello {{ name }}</span>`.

**Comment by circlingthesun** [comment]
@crisbeto are you on rc2? I've not experienced this.

**Comment by crisbeto** [comment]
Yes I am, are you using custom interpolation? Since our backend is on Django, I had to use `{[{ }]}` so that might be causing it.
Also the exact case where I'm using it is `<a href="#" translate>About {[{ ::'BRAND_NAME' | const }]}</a>`, although it happened with just a string or with a variable.

**Comment by circlingthesun** [comment]
Could it be the one time binding? What if you remove '::'?

**Comment by crisbeto** [comment]
The problem is still there if I remove the one-time binding.

**Comment by circlingthesun** [comment]
Mmm.. I'm not using custom interpolation. I don't think that should be an
issue though.

**Comment by crisbeto** [comment]
I can try to isolate it in a fiddle.

**Comment by circlingthesun** [comment]
That would probably be insightful

**Comment by crisbeto** [comment]
It really was insightful. It turns out that the problem is only when using `loadRemote`. Here's the plunk with a mocked backend http://plnkr.co/edit/GHsYC1PwBhiGdf3wwMQL?p=preview.

**Comment by circlingthesun** [comment]
Thats really strange.

**Comment by crisbeto** [comment]
It might be a race condition, because if I wrap `setCurrentLanguage` in a `$timeout` it works fine:

```javascript
$scope.setLanguage = function(key){
 gettextCatalog.loadRemote(key).then(function(){
   $timeout(function(){
     gettextCatalog.setCurrentLanguage(key);
   });
 });
};
```

**Comment by circlingthesun** [comment]
@crisbeto noticed this issue in production. There is definitely a duplicate issue.

**Comment by crisbeto** [comment]
Maybe we should make a new issue since this thread is kinda getting out of the original topic.

**Comment by circlingthesun** [comment]
I created a new issue at #195

**Comment by circlingthesun** [comment]
@crisbeto your multi-line extraction issue might be fixed by https://github.com/angular/angular.js/blob/master/CHANGELOG.md#compile-due-to
