### ISSUE TITLE
Annotating strings in Javascript code

### ISSUE THREAD

**Issue by t00f** [rubenv/angular-gettext#19]
Hello,

Thanks a lot for this useful work ! I always enjoyed the use of gettext, and using it with angular is awesome.

According to the documentation, we can use gettext factory to annotate strings in Javascript code 

``` javascript
angular.module("myApp").controller("helloController", function (gettext) {
    var myString = gettext("Hello");
    console.log(myString);
});
```

My current string Hello is well find after grunt extraction, translated with Poedit and compiled to be added to the translation.js file. Unfortunately, writing those lines won't actually translate the string Hello. The log message keeps to say "Hello" instead of "Hallo"

I checked the source code and I might found the problem. The factory called gettext simply returns the string. A comment explains that it enables grunt to extract strings without translations

``` javascript
angular.module('gettext').factory('gettext', function () {
    /*
     * Does nothing, simply returns the input string.
     * 
     * This function serves as a marker for `grunt-angular-gettext` to know that
     * this string should be extracted for translations.
     */
    return function (str) {
        return str;
    };
});
```

I tried to use the gettextCatalog to find the translation and its seems to work fine.

``` javascript
angular.module('gettext').factory('gettext', function (gettextCatalog) {
  return function (str) {
    return gettextCatalog.getString(str);
  };
});
```

Is there a problem in Javascript annotation ? Does my changes in your gettext factory a nice solution to you ?

**Comment by tsi** [comment]
@tkrotoff did you find a solution for this?
