### ISSUE TITLE
setCurrentLanguage doesn't change the text in *.js files

### ISSUE THREAD

**Issue by Alir3z4** [rubenv/angular-gettext#192]
`gettextCatalog.setCurrentLanguage` doesn't change the translations of the string that I set for translation in `*.js` files.

All the text extracted/compiled from `*.html` files get changed after `gettextCatalog.setCurrentLanguage` but all the extracted/compiled strings that are in  `*.js` files won't get updated, I have to do `$window.reload(true)` to see the results.

*  Grunt tasks conf: https://github.com/SavandBros/tiwun-mobile/blob/master/Gruntfile.js#L37-L55
* Compiled: https://github.com/SavandBros/tiwun-mobile/blob/master/app/scripts/basement/translations.js 
* JS Annotate Example: https://github.com/SavandBros/tiwun-mobile/blob/master/app/scripts/basement/controllers/menu_controller.js#L19-L36

**Comment by rubenv** [comment]
It's impossible.

The result of `gettextCatalog.getString` is a string, which we cannot update.

Here's what you want to do:

```js
$scope.translations = {
        ar: gettext('Arabic'),
        ca: gettext('Catalan'),
        da: gettext('Danish'),
        ...
};

The `gettext` function marks a string for translation, but does not translate it yet. But it helps the extractor find the strings and add them to your `.pot` file.

Then translate the strings in your views.

```html
{{ lang | translate }}</a>
</li>
```
Where `lang` is one of the strings you annotated with `gettext()`.

If you're using a `select` tag, I recommend something like this:

```js
$rootScope.translate = gettextCatalog.getString;
```

```html
<select ng-model="language.selected, ng-options="id as translate(label) for (id, label) in translations" required />
```

**Comment by Alir3z4** [comment]
@rubenv What you said completely makes sense.

However, I tried your approach it didn't work as expected, I got the bellow error in browser console:
```
TypeError: this.getStringForm is not a function
    at Scope.catalog.getString [as trans] (angular-gettext.js:103)
    at $parseFunctionCall (angular.js:12404)
    at callExpression (angular.js:25846)
    at render [as $render] (angular.js:26005)
    at Object.ngModelWatch (angular.js:23423)
    at Scope.$get.Scope.$digest (angular.js:14300)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)
    at XMLHttpRequest.requestLoaded (angular.js:9829)
```
I played with it for a while and found out how to fix it, below is what I've done:
So, I removed `$rootScope.translate = gettextCatalog.getString;` from the controller. and used translate filter from `angular-gettext` in `NgOptions` just like a filter.

```
<select
    ng-model="translation.selected"
    ng-change="changeTranslation(translation)"
    ng-options="k as v|translate for (k, v) in translations"
    ng-init="translation.selected=defaultTranslation">
</select>
```

Although still I'm not sure why your approach of setting `gettextCatalog.getString;` to `$scope`/`$rootScope` didn't work and caused that error.

My problem has been solved now, please feel free to close this issue.

Thank you for your help and explanations.

**Comment by rubenv** [comment]
My bad, wrote this very early in the morning.

Just checked what we do in our project and it's this:

```js
$rootScope.translate = function (str) { return gettextCatalog.getString(str); };
```

**Comment by rubenv** [comment]
But well, the filter is probably a better (cleaner) way to do this. Happy you got it working!
