### ISSUE TITLE
Multiple concurrent translations on bindings

### ISSUE THREAD

**Issue by circlingthesun** [rubenv/angular-gettext#195]
With Angular 1.4.0-rc2 multiple translated strings show up on elements that have bindings when changing the language. The issue is reproduced here: http://plnkr.co/edit/GHsYC1PwBhiGdf3wwMQL?p=preview

The issue may be related to executed order as using $timeout in the snippet below appears to hide the problem:

```js
$scope.setLanguage = function(key){
 gettextCatalog.loadRemote(key).then(function(){
   $timeout(function(){
     gettextCatalog.setCurrentLanguage(key);
   });
 });
};
```

**Comment by circlingthesun** [comment]
@crisbeto, 1.4.0 was just released and it appears to resolve the issue: http://plnkr.co/edit/rgnslpaUvaqUz0nTgM2O?p=preview

**Comment by crisbeto** [comment]
Looks like it, tried it out and haven't seen anything wrong yet.
