### ISSUE TITLE
translate text in placeholder

### ISSUE THREAD

**Issue by nielvrom** [rubenv/angular-gettext#197]
I'm using the plugin angular-gettext but I'm having troubles knowing how to translate the placeholder. This works:
```
<legend translate>Lower secondary studies</legend>
```
When I run grunt the string is added to the .POT file and I can export it to en.po , ... .

But I also have the following input field:
```
<input ng-model="application.lwsdegreeTitle" type="text" placeholder="Degree title" name="lwsappdegreetitle" id="lwsappdegreetitle" />
```

As you can see I have a placeholder with text: Degree title. I've tried adding the attribute translated to the input field but the string doesn't get inserted in the .pot file. I also tried the following:

```placeholder="{{ Degree title}}"``` but no success. How can I fix this?

**Comment by circlingthesun** [comment]
Try this:
```ng-attr-placeholder="{{'Degree title'|translate}}"```

**Comment by gabegorelick** [comment]
Yup. Use the `translate` filter.

**Comment by nielvrom** [comment]
When I use ```ng-attr-placeholder="{{ 'Degree title'|translate }}"```and run grunt the string 'Degree title' is located in my .pot file and I can translate this. But when I run the browser there is no placeholder in my input field.. . It's just empty. And I'm 100% sure the string is translated in the specific .po file for the language.

**Comment by circlingthesun** [comment]
Try using placeholder instead of ng-attr-placeholder.

**Comment by nielvrom** [comment]
Awesome, that works! Thank you very much!
