### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by AkosLukacs** [rubenv/angular-gettext#201]
Hi!
Created a TypeScript definition file for angular-gettext, currently waiting for approval at the DefinitelyTyped repo: https://github.com/borisyankov/DefinitelyTyped/pull/4706 
If you, our anyone else uses TypeScript...

**Comment by crissdev** [comment]
Thanks @AkosLukacs The TypeScript definition file was approved. I'm currently using it without any issues. I guess this issue can be closed now.

**Comment by rubenv** [comment]
:+1:
