### ISSUE TITLE
Port to Polymer

### ISSUE THREAD

**Issue by billymoon** [rubenv/angular-gettext#202]
Since Polymer has reached version 1.0, and does not appear to have a well developed i18n solution (please inform me if I am mistaken!) it might be an idea to port this library.

I expect 80% of code is re-usable, and the other 20% should not be too difficult to port, because the code concepts in Polymer is pretty similar to Angular.

There is an open issue in Polymer at the moment for examples of i18n: https://github.com/Polymer/docs/issues/441

**Comment by gabegorelick** [comment]
Thanks for bringing this up! My initial inclination is that polymer-gettext should be a separate project from angular-gettext. But if someone starts coding it up and it really is a lot of the same code, we can talk about combining forces.
