### ISSUE TITLE
interpolation not working as expected 

### ISSUE THREAD

**Issue by innerpeace0** [rubenv/angular-gettext#211]
* Works as expected. Displays:

> Niets hier

```
<p translate>Nothing here</p>

```
* Works as expected. Displays:

 >nog

```
<p translate>yet</p>

```
* Translates "yet", but not "Nothing here". Displays:

>Nothing here nog

```
<p translate>Nothing here {{'yet' | translate}}</p>

```
* Doesn't translate anything. Displays: 

>Nothing here yet

```
<p translate>Nothing here {{'yet'}}</p>

```
[Codepen here] (http://codepen.io/InnerPeace0/pen/rVREXr)

**Comment by rubenv** [comment]
```
<p translate>Nothing here {{'yet' | translate}}</p>
```

Why would you even want to do such a thing?

**Comment by innerpeace0** [comment]
> Why would you even want to do such a thing?

It was just a test. A variable would probably be used in real life, but the same concept should apply. I just extended the codepen to use a variable, `var testVar = 'yet';` and that didn't work, either.

**Comment by rubenv** [comment]
Can we stick to real-life use-cases? Exploring every possible permutation of things is a fine exercise (and I'll happily accept pull requests that fix any problems), but it won't help us in developing real-life applications.

**Comment by innerpeace0** [comment]
Using a partial string plus a variable would be a common real life case for my single page apps. I've been doing it with JS since JS 1.1. Now, I'm upgrading them to AngularJS, and I want to internationalize them. So far, angular-gettext has most of what I'm looking for.

**Comment by innerpeace0** [comment]
Closed by mistake.

**Comment by innerpeace0** [comment]
> Why would you even want to do such a thing?

@rubenv, I've been thinking about this question all day, and I realized that, while a sequence like "nothing here ___ [today, yesterday, yet, etc.]" might work fine in English, it might end up being back asswards in some other languages. 

So, to properly internationalize my apps, I'll need to put aside my English centric and some of my Don't Repeat Yourself thinking, repeat some of my words, and use complete thoughts rather than chopping my strings into such small pieces.

Consequently, I think I'll be able to use angular-gettext as it is. Thank you for your great work and your patience with a newbie to i18n.

**Comment by rubenv** [comment]
For those cases I generally make an object of labels in a controller, which I then switch on in the view:

```js
var labels = {
     today: gettext("Nothing here today"),
     yesterday: gettext("Nothing here yesterday"),
     earlier: gettext("Nothing here earlier"),
};
```

And in your view:
```
{{ labels[timeframe] | translate }}
```

This is much better than trying to compose strings, as some languages might flip the order of words depending on the context. As you said, slightly more duplication, but it's natural language, that's always messy :-)

More info here: https://angular-gettext.rocketeer.be/dev-guide/annotate-js/

**Comment by innerpeace0** [comment]
Thank you so much, @rubenv. That should give me everything I need. 

Keep up the great work.
