### ISSUE TITLE
Best practice for annotating array of strings in controllers

### ISSUE THREAD

**Issue by jaymanned** [rubenv/angular-gettext#227]
I'm new to gettext so prehaps this question doesn't make too much sense. I'm frequent find myself **initializing** model data for UI components (e.g. selects) in the controllers as arrays of strings. From the developer guide and a couple of posts I read, I understand I have to use `gettext()` to annotate each string so they can be extracted for translation. So this array:

```this.sizes = [
    "Large",
    "Regular",
    "Compact"
];```

should be annotated like this:

```this.sizes = [
    gettext("Large"),
    gettext("Regular"),
    gettext("Compact")
];```

However, shall this code make it to my final build or am I supposed to write a grunt task to get rid of all the  `gettext()` for release? What's the best practice? 

P.D. *Congrats for developing such handy tool. It really makes life easier.*

**Comment by rubenv** [comment]
> However, shall this code make it to my final build or am I supposed to write a grunt task to get rid of all the gettext() for release? What's the best practice?

It will make it in but it is harmless. You may remove it (after extraction) and a grunt task would be a great way to do it. Nobody has written one that I'm aware of.

**Comment by jaymanned** [comment]
Hi Ruben, you're right, I've checked the code. So I guess I'll leave them in ther unless when end up with a huge amount and need to consider Grunt removal. Thanks

**Comment by rubenv** [comment]
Good luck!
