### ISSUE TITLE
getStringForm documentation typo?

### ISSUE THREAD

**Issue by pakal** [rubenv/angular-gettext#231]
I think there is an error in that comment:

    getStringForm(string, n)
        Get the correct pluralized (but untranslated) string for the value of n

Because from the code below, it rather seems that getStringForm() returns a TRANSLATED (potentially PLURALIZED) string, just not $interpolated as getString() does it in addition.

        getStringForm: function (string, n) {
            var stringTable = this.strings[this.currentLanguage] || {};
            var plurals = stringTable[string] || [];
            return plurals[n];
        },.

**Comment by rubenv** [comment]
I think you are right!

**Comment by rubenv** [comment]
Fix pushed, thanks for reporting this!
