### ISSUE TITLE
Problem with Russian plurals

### ISSUE THREAD

**Issue by losferwords** [rubenv/angular-gettext#234]
Strange problem. Serfing for solution some days, nothing helpfull.

I created this line (just for test) in my .ejs file :

<p translate translate-n="testCounter" translate-plural="You got {{$count}} new messages">You got new message</p>

testCounter is just a scope variable and I change it dynamically with buttons + and -

I create .po file with POEdit which contains next:
msgid ""
msgstr ""
"Project-Id-Version: FOTM\n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: ru_RU\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.6\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Poedit-Basepath: .\n"

#: template/partials/login.ejs:29
msgid "You got new message"
msgid_plural "You got {{$count}} new messages"
msgstr[0] "У вас {{$count}} новое сообщение"
msgstr[1] "У вас {{$count}} новых сообщения"
msgstr[2] "У вас {{$count}} новых сообщений"

But when I start my app and try to increase testCounter, I get next:

У вас 0 новых сообщения - wrong form
У вас 1 новое сообщение - right form
У вас 2 новых сообщения - right form
У вас 3 новых сообщения - right form
У вас 4 новых сообщения - right form
У вас 5 новых сообщения - wrong form
У вас 21 новых сообщения - wrong form

It seems, that rule (n%10==1 && n%100!=11) work only with "1 message" and msgstr[2] never apply.

In translations.js plurals seems right:

angular.module('gettext').run(['gettextCatalog', function (gettextCatalog) {
/* jshint -W100 */
    gettextCatalog.setStrings('ru_RU', {"You got new message":["У вас {{$count}} новое сообщение","У вас {{$count}} новых сообщения","У вас {{$count}} новых сообщений"]});
/* jshint +W100 */
}]);

Angular version: 1.4.3
Angular-gettext version: 2.1.0

Sorry if something wrong, my first Git issue.
Thanx for help)

**Comment by rubenv** [comment]
Hi!

Thanks for reporting this (and congratulations with your first issue reported!).

I think the problem here is that we don't support subcodes yet: `ru_RU` is unrecognized. I really want to fix it, but I haven't had the time for it yet.

Could you try using `ru` as the language?

```js
gettextCatalog.setStrings("ru", {"You got new message":["У вас {{$count}} новое сообщение","У вас {{$count}} новых сообщения","У вас {{$count}} новых сообщений"]});


gettextCatalog.setCurrentLanguage("ru");
```

That should do the right thing.

Let me know if that fixes things (for now).

**Comment by losferwords** [comment]
Oh, man! Great thanks to you for your answer!

Change to gettextCatalog.setCurrentLanguage('ru') and Choose in PoEdit translate language from (Россия (русский)) to (Россия).

All that fixed problem and now all plurals work completely right.

Thank you for this great angular module, it helps my russian mates to undestand spells in my game XD

Issue closed.

**Comment by rubenv** [comment]
Great, this shouldn't be a problem anymore in the future, but for now I'm happy that you have a working fix.

Good luck with it!
