### ISSUE TITLE
loadRemote not exposing the response data

### ISSUE THREAD

**Issue by crisbeto** [rubenv/angular-gettext#238]
When trying to do something like this:

```javascript
gettextCatalog.loadRemote('something').then(function(response){
  console.log(response);
});
```

The server response is `undefined`, because `loadRemote` returns the promise as `return $http.get(...).then()`. In order to be able to get the data, the response needs to return either the promise itself or return the `response` in the `then` handler. 

I've submitted a PR with the fix for this. The fix can be written shorter, but I went with this approach so it's a little bit more obvious what's going on.

**Comment by rubenv** [comment]
Is there any reason why you'd ever want to do this?

**Comment by crisbeto** [comment]
The way I'm using it is that I have a wrapper around `loadRemote` that also caches the translations in `localStorage` after they got loaded.

**Comment by crisbeto** [comment]
Also it doesn't really hurt anything by letting you access the data that just got loaded.

**Comment by rubenv** [comment]
> The way I'm using it is that I have a wrapper around loadRemote that also caches the translations in localStorage after they got loaded.

Oh, that makes sense!
