### ISSUE TITLE
Do you have plan to support bundle or namespace on translating?

### ISSUE THREAD

**Issue by bruceman** [rubenv/angular-gettext#240]
Hi Ruben,
Do you have plan to support bundle or namespace on translating?
You know there are maybe have multiple same string but have different translated string in big project.
One solution for this case is using bundle name or namespace to get suitable string resource.
For example:
1. for directive
<span translate="mybundle" ..>
2. for filter
{{ msg | translate:"mybundle"}}

Thanks,

**Comment by rubenv** [comment]
Have a look at translation contexts, those solve the problem you're
mentioning.

**Comment by bruceman** [comment]
Thanks Ruben,
But as i understood, the context is just for accessing nested properties. i can not find a way to isolate the translated string from multiple i18n files.

**Comment by rubenv** [comment]
> i can not find a way to isolate the translated string from multiple i18n files.

You shouldn't the whole point of gettext is that same source strings can be combined. In the rare event of clashes (noun vs. verb etc), contexts are what helps you.

As mentioned in #241: we probably won't add this, it makes things needlessly complex. More details in #115 and linked issues.
