### ISSUE TITLE
$state.reload instead of broadcastUpdate?

### ISSUE THREAD

**Issue by vbraun** [rubenv/angular-gettext#242]
Background: I'm having some interop issues with angular-material, e.g. #214 or https://github.com/angular/material/issues/1742. In both cases the initial render is ok, but subsequent changes of the language via `setCurrentLanguage(...)` don't produce the desired effect.

My current workaround is to just flip the language variable and reload the current state:

        gettextCatalog.currentLanguage = ...
        $state.reload()

I realize that this uses ui-router and loses content of `<input>` fields, on the other hand it is more robust since you only have to be able to render once. Another advantage is that you can use one-time bindings `{{::"Text"|translate}}`. Is there any other issue that I haven't thought about? Would there be interest to "bless" this workaround by adding a special setter `setCurrentLanguageAndReload`, say?

**Comment by rubenv** [comment]
I'm not sure why changes to angular-gettext are needed for this?

Can't you just add this to your application:

```js
$rootScope.$on("gettextLanguageChanged", function () {
    $state.reload();
});
```
?

**Comment by rubenv** [comment]
Also note that there isn't currently a dependency on ui-router in angular-gettext (and we won't add one, not every project needs ui-router).

**Comment by vbraun** [comment]
Good idea, I didn't think about overwriting the gettextLanguageChanged signal!

I'm still having some issues with

     <md-button translate>Text</md-button>

in angular-material. This is first hit by the angular-material compiler,  which rewrites it to

     <md-button translate><span>Text</span></md-button>

and then angular-gettext can't extract the msgid. It should run first so it can access the untransformed "Text". And then it must not terminate so that angular-material can do its thing. I'm currently playing around with changing

         restrict: 'AE',
    -    terminal: true,
    -    terminal: false,
    +    priority: 10000,
         compile: function compile(element, attrs) {

in the translate directive. Should this be configurable? I read #147 but I still don't know why it sets terminal=true right now.

**Comment by arsonik** [comment]
any update on that issue ?

**Comment by rubenv** [comment]
@vbraun That's a different discussion, which we should probably have in #147.

We could probably tweak both values, but I'm hesitant to do so because I'm not entirely sure what the effects might be (and I don't want to break existing code out there). If we can prove that it's safe: sure.

**Comment by rubenv** [comment]
As for the state switching, that seems solved, so I'll be closing this issue (feel free to reopen if needed).
