### ISSUE TITLE
Chaining filters  in interpolation creates invalid msgid strings in  POT file

### ISSUE THREAD

**Issue by clue42** [rubenv/angular-gettext#243]
If filters are chained in interpolations like:

h2 {{"This is a string" | test | translate}}

The output of the related msgid in the POT file is then containing html text from the subsequent lines in the template like:

`msgid "This is a string\" | test | translate}}</h2><form novalidate=\"novalidate\" role=\"form\" name=\"loginForm\" ng-submit=\"login.onLogin(loginForm)\" class=\"login-form\"><div ....`

This even happens if there is not a chain of filters but just a filter other than the translate filter.

NOTE: This seems to be an angular-gettext-tools issue in the extractor rather than an issue of angular-gettext itself.

**Comment by rubenv** [comment]
> h2 {{"This is a string" | test | translate}}

I'm not even sure this makes sense. What does the test filter do?
If it makes any change to the source string, it'll cause translation to fail.
