### ISSUE TITLE
Gettext constant

### ISSUE THREAD

**Issue by MigFerreira** [rubenv/angular-gettext#244]
Is there no better way than to have gettext as a constant function?
This forces it to be injected anywhere its to be used, and all it does is serve as a marker...

For example if i have text in constant object that needs translation if forces me to make that constant a service just so i can inject gettext.

Also is this not an unecessary overhead for nothing... since you are calling a function that returns the exact parameter you are passing in?

**Comment by circlingthesun** [comment]
If I'm not mistaken, any function named gettext should work with the
extractor. So you should be able to write your own.

**Comment by rubenv** [comment]
In terms of runtime overhead the effect should be zero: any decent
JavaScript implementation will recognize that this is a noop and inline it.

**Comment by MigFerreira** [comment]
Think im going to create my only global gettext noop func.
Thanks for the quick and clear answers.
