### ISSUE TITLE
Allow parameters to be passed when interpolating within the directive

### ISSUE THREAD

**Issue by milica** [rubenv/angular-gettext#254]
Hi there!

I came across the issue using `translate` directive, when using it in a way to interpolate certain values.
I believe that it should work the same as `angular-translate`'s directive, by passing parameters through dedicated attribute, like `translate-values`. Without this it's not possible to use directive with hardcoded values but still repetitive. For example I'm listing this ranking tables with headings:
- top 10 rankings
- top 50 rankings
- top 100 rankings
- top 300 rankings

As you can see `top {{ rank }} rankings` doesn't work for this case, and instead I need to put all 4 sentences into translation files which is not optimal.

**Comment by rubenv** [comment]
You could do something like this:

```js
$scope.rankings = [
    { count: 10 },
    { count: 50 },
    { count: 100 },
    { count: 300 },
];
```

```html
<div ng-repeat="rank in rankings">
    <a href="..." translate translate-n="rank.count" translate-plural="top {{$count}} rankings">Top 1 ranking</a>
</div>
```

Which has the added benefit of returning correct plurals in all languages.

**Comment by milica** [comment]
True, that should solve the case I have. Easy solution :)
Thanks!
