### ISSUE TITLE
Extract strings from TypeScript files

### ISSUE THREAD

**Issue by DirkAmmerlaan** [rubenv/angular-gettext#258]
Hi Ruben,

I am working on a webapp where we are currently rewriting all of our JS files to TypeScript. We are using the following Type Definitions for Angular-gettext (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angular-gettext/angular-gettext.d.ts). Now it seems that translations defined in the JS files are no longer extracted. I've added the *.ts files to be scanned as well, but it does not seem to work. Do you have any idea if this is possible and how we can make it work?

Thanks in advance!

**Comment by rubenv** [comment]
Extraction is handled by angular-gettext-tools: https://github.com/rubenv/angular-gettext-tools

I don't think it supports Typescript yet, but I will gladly accept a pull request that adds Typescript support!

**Comment by DirkAmmerlaan** [comment]
Thanks for your quick answer! :)

At the moment I am working around the issue, defining translations in the HTML instead of the JS/TypScript files. We may look into fixing it later and provide you with a nice PR. But I don't promise anything yet ;)

**Comment by rubenv** [comment]
Note that we generally recommend an in-between step for languages such as CoffeeScript: transpile your code to JS (you'll need to do that anyway for browsers), then extract the strings from them.

**Comment by DirkAmmerlaan** [comment]
Exactly. 

We are also refactoring our build tooling since we are using both gulp and grunt. We are moving to Webpack and will add this extract step right after the transpile step.
