### ISSUE TITLE
Use filter on variables in strings?

### ISSUE THREAD

**Issue by devboxr** [rubenv/angular-gettext#276]
Hi guys,

the forum here does not seem to be very active, but I hope somebody can help me.

This is very simplified example:

```js
{
    unitPrice: 19.99
    currency: 'GBP'
}
```

```html
<p translate>Total Amount: {{totalAmount}}</p>
```

Now, I want to use the `currency` filter on the `unitPrice` and replace it in the HTML-paragraph.

Any idea how to do this?

This is what I tried:

```html
<p translate="Description test 123. Unit Price: {{ unitPrice | currency:'£':2 }}"></p>
```

But of course then you have PO files that look like this:

```po
#: public/views/checkout/form_partials/_product.html:57
msgid "Description test 123. Unit Price: {{ unitPrice | currency:'£':2 }}"
msgstr ""
```

Thanks!

**Comment by IShotTheSheriff** [comment]
I see you've left this message quite a long time ago @devboxr and you probably already get your own solution but I had the same problems you can check out my approach here: https://github.com/rubenv/angular-gettext/issues/285 .

**Comment by devboxr** [comment]
@IShotTheSheriff Hi there, thanks! I indeed found a different solution and switched to another framework in the meantime. Thanks though!
