### ISSUE TITLE
Lazy loading compile doesn't produce anything

### ISSUE THREAD

**Issue by Janjuks** [rubenv/angular-gettext#278]
So far love the library. Used it without lazy loading and everything worked like a charm, but with lazy loading it doesn't seem to compile anything. Console message shows `Done, without errors`, but no json files are generated.

    nggettext_compile: {
        all: {
            options: {
                format: "json"
            },
            files: [
                {
                    expand: true,
                    dot: true,
                    cwd: "po",
                    dest: "Scripts/translations/languages",
                    src: ["Scripts/translations/pot/*.po"],
                    ext: ".json"
                }
            ]
        },
    },

I don't know what else I should provide. Yes, there are *.po files in `Scripts/translations/pot` directory.
Btw, what do options expand, dot, cwd mean? Is this documented anywhere?

**Comment by rubenv** [comment]
Grunt is a pain, I've been using it for a long time and I still need the docs to work out how those options work. All you need should be here: http://gruntjs.com/configuring-tasks

**Comment by Janjuks** [comment]
Ah, thanks! I'm new to grunt thanks to you and tought thought that those are library specific options.
In my case I had to comment out `cwd: "po"` and add flatten:true so that the source path isn't copied to destination
