### ISSUE TITLE
Error: [$injector:unpr] only in env prod

### ISSUE THREAD

**Issue by Nexyssify** [rubenv/angular-gettext#280]
Hello,

I have this probleme : 
"Error: [$injector:unpr] Unknown provider: translateFilterProvider <- translateFilter.

But I have it only porduction Environnement. 

Do you know why ?

**Comment by rubenv** [comment]
Hard to tell without code. Can you make a jsFiddle example?

**Comment by Nexyssify** [comment]
`var baseUrl = Routing.generate('app_homepage');


var app = angular.module('app', [
    'ngRoute',
    'mm.foundation',
    'ngResource',
    'ngFileUpload',
    'ui.date',
    'nvd3',
    'ngCropper',
    'ui.router',
    'gettext'
]).config(config).run(['$window', '$rootScope', 'gettextCatalog',
    function ($window ,  $rootScope, gettextCatalog) {
        $rootScope.goBack = function(){
            $window.history.back();
        };

        var locale = 'en';
        var nameEQ = "language" + '=';
        var cookie = document.cookie.split(';');
        
        for (var i = 0; i < cookie.length; i++) {
            var c = cookie[i];
            while (c.charAt(0) === ' ')
                c = c.substring(1,c.length);
            if (c.indexOf(nameEQ) === 0)
                locale = c.substring(nameEQ.length,c.length);
        }

        console.log(locale);

        FastClick.attach(document.body);
        moment.locale(locale);
        gettextCatalog.setCurrentLanguage(locale);
        gettextCatalog.debug = true;
    }
]);`

` {% javascripts output='assets/compiled/frontend.js' filter='?uglifyjs2'
'@WebBundle/Resources/assets/bower_components/angular-gettext/dist/angular-gettext.min.js'
%}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}`

I have this. This is help you ? 

And I have this complet error:
`"Error: [$injector:unpr] Unknown provider: translateFilterProvider <- translateFilter
http://errors.angularjs.org/1.3.17/$injector/unpr?p0=translateFilterProvider%20%3C-%20translateFilter
minErr/<@http://localhost/assets/compiled/frontend.js?v1:63:12
createInjector/providerCache.$injector<@http://localhost/assets/compiled/frontend.js?v1:4031:19
getService@http://localhost/assets/compiled/frontend.js?v1:4178:39
createInjector/instanceCache.$injector<@http://localhost/assets/compiled/frontend.js?v1:4036:28
getService@http://localhost/assets/compiled/frontend.js?v1:4178:39
$FilterProvider/this.$get</<@http://localhost/assets/compiled/frontend.js?v1:16724:14
Parser.prototype.filter@http://localhost/assets/compiled/frontend.js?v1:12242:14
Parser.prototype.filterChain@http://localhost/assets/compiled/frontend.js?v1:12236:14
Parser.prototype.statements@http://localhost/assets/compiled/frontend.js?v1:12215:25
Parser.prototype.parse@http://localhost/assets/compiled/frontend.js?v1:12072:17
$parse@http://localhost/assets/compiled/frontend.js?v1:12789:32
$interpolate@http://localhost/assets/compiled/frontend.js?v1:10168:25
addAttrInterpolateDirective@http://localhost/assets/compiled/frontend.js?v1:8133:27
collectDirectives@http://localhost/assets/compiled/frontend.js?v1:7235:13
compileNodes@http://localhost/assets/compiled/frontend.js?v1:7067:22
compileNodes@http://localhost/assets/compiled/frontend.js?v1:7083:15
compileTemplateUrl/<@http://localhost/assets/compiled/frontend.js?v1:8001:38
processQueue@http://localhost/assets/compiled/frontend.js?v1:13300:27
scheduleProcessQueue/<@http://localhost/assets/compiled/frontend.js?v1:13316:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost/assets/compiled/frontend.js?v1:14555:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost/assets/compiled/frontend.js?v1:14371:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost/assets/compiled/frontend.js?v1:14660:13
done@http://localhost/assets/compiled/frontend.js?v1:9734:36
completeRequest@http://localhost/assets/compiled/frontend.js?v1:9924:7
requestLoaded@http://localhost/assets/compiled/frontend.js?v1:9865:1
"`

**Comment by Nexyssify** [comment]
Sorry for the format

**Comment by Nexyssify** [comment]
But my code works well in dev environement.

**Comment by rubenv** [comment]
This looks like a problem with your compilation setup rather than with angular-gettext.
I'm afraid I can't help you out with this.

**Comment by rubenv** [comment]
You might find more help here: https://docs.angularjs.org/error/$injector/unpr

**Comment by Nexyssify** [comment]
Ok Thank's, do you know wky translation work on Dev environment and not on Prod ?
