### ISSUE TITLE
Translating doesn't work in a Factory/service

### ISSUE THREAD

**Issue by suku-v** [rubenv/angular-gettext#282]
gettextCatalog.getString() is not working in a factory/service

`angular.module('myapp').controller('searchController', ['gettextCatalog', 'gettext',` 
`function(gettextCatalog, gettext) {`
    `console.log(gettextCatalog.getString('search')); // it is working fine in a controller`
`}])`

Not working in case of factory/service

`angular.module('myapp')`
`.factory('searchConstants', ['gettext', 'gettextCatalog', function(gettext, gettextCatalog){`
   `return{`
        `search: gettextCatalog.getString(gettext('search'))`
   `};`
`}])`
`.controller('searchController', [function() {`
    `console.log(searchConstants.search); // Not getting translated string`
`}]);`

Please look into the issue.

**Comment by nloyola** [comment]
Please explain why you closed this issue. Does `gettextCatalog.getString()` actually work correctly in factories and services?

**Comment by nloyola** [comment]
It seems this issue was already reported in #180.

**Comment by aprocom** [comment]
gettextCatalog.getString() works fine everywhere but don't forget about step:
gettextCatalog.setStrings()
