### ISSUE TITLE
Colspan causes multiple spans to be produced

### ISSUE THREAD

**Issue by inthegarage** [rubenv/angular-gettext#283]
The following simple(ish) code:

```
                        <thead>
                           <tr>
                               <th colspan="3" class="box">
                                  <span translate>Header</span>
                               </th>
                          </tr>
                         </thead>``
```
Produces multiple spans with MISSING items:
```

<thead>
                        <tr role="row" class="ng-scope"><th class="box audit-column" colspan="3" rowspan="1">
                                <span translate=""><span class="ng-scope">[MISSING]: </span><span class="ng-scope">[MISSING]: </span><span class="ng-scope">Header</span></span>
                            </th
                    </thead>
```

A workaround is to do the following:
       `  <span>{{'Audit traixxxxl'|translate}}</span>`

Tested with latest version of angular-gettext. 2.2.1
Please investigate.

**Comment by rubenv** [comment]
There's no way the first code can turn into the second code with just angular-gettext (for instance, we don't know anything about `audit-column`).

You probably have some other directives in there that transclude in a wrong way. Either way, this isn't an angular-gettext issue per se.

**Comment by inthegarage** [comment]
angular-gettext appears to be fine without the colspan attribute, so I'm a little confused. So for instance:

```
                        <tr>
                            <th class="box" translate>Date</th>
                            <th class="box" translate>Status to</th>
                            <th class="box audit-column" translate>Comment</th>
                        </tr>
```
Works just fine. This is in an angular-datatable so I guess this will be something too. It's difficult to track down what is going wrong though.

**Comment by inthegarage** [comment]
Note audit-column is not a directive and just a class.

**Comment by rubenv** [comment]
> This is in an angular-datatable

I'm guessing that one doesn't play nice with other directives.

**Comment by inthegarage** [comment]
Yep, that's my guess. it seems to be fired when you add translate to a tag with a colspan, that datatables has earmarked. My guess is that it adds the columns and then takes them away again. The workaround works as it's probably much later in the digest cycle. I close this for now. I'd imagine that it's a tricky change in datatables. I'll close this and hopefully our comments will help anyone else who stumbles over this issue.
