### ISSUE TITLE
Getting different context in javascript call

### ISSUE THREAD

**Issue by karelbilek** [rubenv/angular-gettext#287]
This might be just a missing feature in the documentation, or a missing feature, I am not sure

I want to use different context with gettext directly in code. Such as this

```
angular.module("myApp").controller("helloController", function (gettextCatalog) {
    var myString = gettextCatalog.getString("Hello");
});
```

I want to use Hello in the context greeting (for example). How do I do that? I want something like, for example

```
var myString = gettextCatalog.getStringContext("Hello", "greeting");
```

or

```
var myString = gettextCatalog.getString("Hello", {context: "greeting"});
```

Something like that. Can angular-gettext do that?

**Comment by runn1ng** [comment]
Oh, it's in the code already, it's just missing in the docs.

So it's the doc issue, not code issue. Which is good.

**Comment by karelbilek** [comment]
closing, stale
