### ISSUE TITLE
Scenario Runner tests broken

### ISSUE THREAD

**Issue by rubenv** [rubenv/angular-gettext#289]
Turns out that the scenario runner is completely broken. Now might be a good time to bite the bullet and convert the tests to Protractor.

**Comment by rubenv** [comment]
@IShotTheSheriff This was breaking your builds in #286, not your code. Working on it.

**Comment by IShotTheSheriff** [comment]
I'm glad because I was also trying to run in couple different variations locally and all test were passing. Tried to restart build but yea, problem seems to be laying in other place.

**Comment by rubenv** [comment]
A clean `bower install` and `npm install` helps reproducing it, sadly.

**Comment by rubenv** [comment]
All protractorized now!
