### ISSUE TITLE
Translate text from a function in view using ng-repeat?

### ISSUE THREAD

**Issue by mosiruane123** [rubenv/angular-gettext#297]
Hi,

I have a slight problem that I can't seem to get passed and I was hoping someone could help!

I have a function with the following array:
              scope.channels = [
                           {icon: 'call', name: 'Voice', selected: false},
                           {icon: 'chat', name: 'Web-Chat', selected: false},
                           {icon: 'email', name: 'Email', selected: false},
                           {icon: 'textsms', name: 'SMS', selected: false}
               ];

and in my view, I iterate over the items using ng-repeat:

 <md-list-item ng-repeat="channel in channels">
      <md-icon> {{ channel.icon }} </md-icon>
      <p> {{ channel.name }} </p>

I was hoping I could apply some form of translate filter like {{ channel.name | translate }} but it doesn't seem to work.

Is there any way I can translate 'Voice', 'Web-Chat', 'Email' and 'SMS' in the above scenario?

Any help would be greatly appreciated.

**Comment by rubenv** [comment]
Annotate them with gettext():
https://angular-gettext.rocketeer.be/dev-guide/annotate-js/

**Comment by mosiruane123** [comment]
Brilliant! Got it working
