### ISSUE TITLE
Missing translation in js code for Angular Material mdToast

### ISSUE THREAD

**Issue by clemator** [rubenv/angular-gettext#319]
Hey !

In my toast factory, I am looking for a string 'CLOSE' to put the translation in a toast.
My problem is that it is always marked as [MISSING] when the key and value are in my translation json files !

Here is how I proceed :

```
function logger($log, $mdToast, gettext, gettextCatalog) {
    var close = "CLOSE";
    close = gettextCatalog.getString(close);
    close = gettext(close);

    var service = {
      showToasts: true,
      error: error
    };

    function error(message, data) {
      message = gettext(message);
      $mdToast.show(
        $mdToast
          .simple()
          .textContent(message)
          .theme('error-toast')
          .action(close) // <-- MISSING
          .highlightAction(true)
      );
      $log.error('Error: ' + message, data);
    };
    return service
}
```

**Comment by rubenv** [comment]
```js
    var close = "CLOSE";
    close = gettextCatalog.getString(close);
    close = gettext(close);
```

This makes no sense.

Better would be:

```js
    function error(message, data) {
      message = gettext(message);
      $mdToast.show(
        $mdToast
          .simple()
          .textContent(message)
          .theme('error-toast')
          .action(gettextCatalog.getString("CLOSE"))
          .highlightAction(true)
      );
      $log.error('Error: ' + message, data);
    };
```

**Comment by clemator** [comment]
Ok it works, thanks, but I have a question, what is the difference between gettextCatalog.getString() and gettext() ?

**Comment by rubenv** [comment]
All explained here: https://angular-gettext.rocketeer.be/dev-guide/annotate-js/

**Comment by clemator** [comment]
I already read that, but to be sure, gettext() add the string to the .pot file and gettextCatalog.getString() get the translation from the translation file, is that right ?

**Comment by rubenv** [comment]
Yes.

Mostly you'd do something like:

```
$scope.something = gettext("Hello");
```

```
<span>{{something | translate}}</span>
```

That's the best way to do things, since it'll update the span if the language changes.

Only use `gettextCatalog.getString()` if you need a translated version to pass it into e.g. a library (such as `$mdToast`).

**Comment by clemator** [comment]
OK thanks, I understand now.
Good day !
