### ISSUE TITLE
Translations containing ONLY param doesn't translate

### ISSUE THREAD

**Issue by cakeinpanic** [rubenv/angular-gettext#326]
```
catalog.setStrings("nl", {
      somekey: "{{name}}"
});
$scope.myName= 'Katerina';
<div translate translate-params-name="myName">somekey</div>
```
Translation doesn't appear at all
I found out that [this condition](https://github.com/rubenv/angular-gettext/blob/master/src/directive.js#L131) causes this

I've tried to fix it, but don't fully understand the reason of this check, so i'd like to discuss it with author

**Comment by msubotic** [comment]
Having the same issue.

**Comment by brumargues** [comment]
We have the same issue in here, only works if you give a space in the beginning or at the end of the interpolated string.

```html
<div translate translate-params-name="myName">{{name}}</div>
```
So solutions that works:
```js
"{{name}}":{
      "Name":" {{name}}"
}
// or
"{{name}}":{
      "Name":"{{name}} "
}
```
Where it fails:
```js
"{{name}}":{
      "Name":"{{name}}"
}
```
