### ISSUE TITLE
Missing  'me' locale (Montenegrin)

### ISSUE THREAD

**Issue by vesko-vujovic** [rubenv/angular-gettext#327]
Can you add **me** locale to your library?

**Comment by rubenv** [comment]
There's no definition for it?

http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms

**Comment by vesko-vujovic** [comment]
Serbian and Montenegrin are same language....  So same rules for both languages.

Can you just add it to your library? 

I added me locale like this in your factory("gettextPlurals"), it works fine.

But if someone make a commit i will lose this change.  

```
case "be":  // Belarusian
            case "bs":  // Bosnian
            case "hr":  // Croatian
            case "ru":  // Russian
            case "sr":  // Serbian
            case "me":  // Montenegrin
```
            case "uk":  // Ukrainian

**Comment by rubenv** [comment]
I'm not up-to-date on the matter. If it's the same language, why not just use Serbian?

**Comment by vesko-vujovic** [comment]
They use the same rules for plural form, dialect is different.  Adding this line `  case "me":  // Montenegrin` would save the day. 
Your service, your decision, thanks in advance. :)

**Comment by rubenv** [comment]
Did a quick search and it turns out this request has come up before: #14 

As then, I'd like to stick to ISO-specified languages. See this comment for more reasoning: https://github.com/translate/l10n-guide/pull/7#issuecomment-26495015
