### ISSUE TITLE
Extra <span> tags are breaking bootstrap's buttons, labels, etc

### ISSUE THREAD

**Issue by stockutils** [rubenv/angular-gettext#328]
Hi,

I've started using this library recently but I've seen that many things get broken, especially when using Twitter's bootstrap like "buttons", "labels", etc because it adds an extra <span> tag and hence the CSS does not correctly apply to it.

Is there any way to fix this? Maybe an option during configuration phase that it shouldn't add extra <span> tags?

Thanks!

**Comment by circlingthesun** [comment]
Have you tried angular 1.6? It looks like they might have taken care of the span tags in 1.6. I've not had time confirm it.

**Comment by circlingthesun** [comment]
Angular 1.6 fixes the span issue. See:
Spans in 1.5.9: http://plnkr.co/edit/tKloB8LFk3GCAsu0UEUx?p=preview
No spans in 1.6.0: http://plnkr.co/edit/tE96QrOPtqxuxR4xbxRL?p=preview

**Comment by stockutils** [comment]
Yes, upgrading to angular 1.6 resolves this issue for good! thank you so much @circlingthesun for the updates!
