### ISSUE TITLE
French plural translation for zero elements give the singular form instead of the plural one.

### ISSUE THREAD

**Issue by sdeprez** [rubenv/angular-gettext#329]
For instance with this:
 ```
<p translate translate-n="appleCount" translate-plural="I have {{appleCount}} apples.">
  I have 1 apple.
</p>
```

If `appleCount` equals zero and the active language is French, we'll get the translation for the singular form (j'ai 1 pomme) instead of the plural one (j'ai 0 pommes).

You can see the bug in action here:
http://plnkr.co/edit/RShe2FNB5diCsKnMPUFb?p=preview

Anyway, thanks for this library, very nice to use!

**Comment by rubenv** [comment]
According to http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms, that's the expected behavior for French.

Mozilla has a not about this: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals#French

> Some French speaking places treat 0 as plural while others treat it as singular. The only other singular is 1 while everything else is plural. So pick either plural rule #1 or #2.

I'd love to stick to whatever is the standard here. Can we find a professional French translator to weigh in on this?

**Comment by sdeprez** [comment]
Oh I see. I thought that it was a bug because since my singular string is "I have 1 apple", I was getting the "J'ai 1 pomme" for `n = 0` in French, but I can fix that by using a singular form `I have {{$count}} apple`, because I don't really care about having an `s` or not. (French is my native language, and I'd say that zero can be singular or plural, depending if you'd usually expect one or more of this given thing, but that's debatable).

Anyway, thanks, as far I'm concerned you can close the issue!

**Comment by rubenv** [comment]
@sdeprez Cool, thanks for the explanation. This issue has come up before and it's a hard thing for me to evaluate. In theory I understand and speak French, but I don't feel confident enough in it to have a good opinion on all the subtleties.

My hope here is that the wider open-source community got it right (or at least usable).
