### ISSUE TITLE
Adding a translation at runtime?

### ISSUE THREAD

**Issue by rdeslonde-eichleay** [rubenv/angular-gettext#351]
Our customers can provide custom messages to their customers on our platform. So we want to enable them to provide their own translations of their custom messages. So at runtime, I would like to add their translation to the catalog. Is that possible?

**Comment by rdeslonde-eichleay** [comment]
I think this answers my question?

https://angular-gettext.rocketeer.be/dev-guide/manual-setstrings/

**Comment by rubenv** [comment]
@rdeslonde-eichleay yes it does, that's exactly the way to go!

**Comment by rdeslonde-eichleay** [comment]
If I already have a bunch of translations from a po file, and I use setStrings, will it clear the translations that already exist and set the new ones, or will it just set the new ones, adding them to the existing set?

**Comment by rubenv** [comment]
Source is here: https://github.com/rubenv/angular-gettext/blob/20d88695a25257764a62131182be271661b7b146/src/catalog.js#L155-L201

It merges.

**Comment by rdeslonde-eichleay** [comment]
Sweet, thanks. This is an awesome library. Thanks for maintaining it.

**Comment by rubenv** [comment]
Thanks, glad you like it. Don't have too much time for it nowadays, but it doesn't ask for much either.

Spread the word!
