### ISSUE TITLE
TypeError: gettextCatalog.setCurrentLanguage is not a function

### ISSUE THREAD

**Issue by susanm74** [rubenv/angular-gettext#364]
I followed this [tutorial*](https://lostechies.com/gabrielschenker/2014/02/11/angularjspart-12-multi-language-support/) without any issue, up until when I tried to call "gettextCatalog.setCurrentLanguage('sw')" in my $scope.changeLanguage function, which is when I get the following console error:
"TypeError: gettextCatalog.setCurrentLanguage is not a function"

*tutorial originally found via this stackoverflow [article](https://stackoverflow.com/questions/25574809/angular-gettext-translation-service-doesnt-appear-to-be-working/25915293#25915293?newreg=f528df66f71c4874aecd8eb7e40e22fc)

**Comment by susanm74** [comment]
Ooh, so I think I figured out the issue!

this controller syntax works:
```
angular.module('myApp').controller('myAppController', 
   function myAppController($scope, gettextCatalog) {
   // do some stuff with gettextCatalog
});
```

but **THIS** controller syntax does **NOT** work:
```
var app = angular.module('myApp');
app.controller('myAppController', ['$scope', 'gettext', myAppController]);
function myAppController($scope, gettextCatalog) {
   // do some stuff with gettextCatalog
}
```

Hope this helps anyone else running into the same issue!

**Comment by rubenv** [comment]
> app.controller('myAppController', ['$scope', **'gettext'**, myAppController]); function myAppController($scope, **gettextCatalog**) {

That's because you have a mismatch between the inject spec and what you try to use. You're injecting `gettext`, which is not the `gettextCatalog` you want.

Not a bug really, more a programmer error. Glad you figured it out!

**Comment by susanm74** [comment]
Yep yep!

this controller syntax works:
```
var app = angular.module('myApp');
app.controller('myAppController', ['$scope', 'gettextCatalog', myAppController]);
function myAppController($scope, gettextCatalog) {
   // do some stuff with gettextCatalog
}
```

Thanks for the follow-up clarification!
