### ISSUE TITLE
Handling grammatical gender with Angular-Gettext

### ISSUE THREAD

**Issue by CharlesHamel** [rubenv/angular-gettext#39]
Hi,

We are starting a big project and thinking seriously about using Angular-Gettext. Our only concern is about handling gender. Is there a  simple-proper-elegant way to do it ?

Thank you very much!

**Comment by flaviodev** [comment]
a solution with context:

without gender:
en: + New Profile
pt: + Novo Perfil

with gender:
en: + New Institute
pt: + **Nova** Instituição

html: 
{{'New' | translate:'female'}} 

translation.js: 
gettextCatalog.setStrings("pt", {
    "New" : {"female":"Nova","male":"Novo",'$$noContext':"Novo" }
}

the '$$noContext' is for simple invocation:
{{'New' | translate'}} 

soved !
