### ISSUE TITLE
How can I translate select options?

### ISSUE THREAD

**Issue by diegomesata** [rubenv/angular-gettext#58]
Hello, I've a select binding to ng-options, How can I translate the item.Name option text?

<select class="form-control" ng-model="task.Type" ng-options="item.Value as item.Name for item in Types"> </select>

I think angular-gettext is great!

**Comment by nlemire** [comment]
Hi, 
I've tested this solution, it works, except for one thing : when I change the language, it dynamically changes the translations of all labels on the screen , except the ones of this ng-options.

is there a trick to make these translations dynamic too ?

thanks :)

(an congratulations for angular-gettext, so easy to implement and powerful !)

**Comment by votemike** [comment]
@rubenv I've come across this issue while trying to solve my own problem. I'm trying to populate a dropdown with quantities, but also allowing a 'Custom' quantity like so:
```
vm.quantityOptions = [
            {value: 1, name: '1'},
            {value: 2, name: '2'},
            {value: 3, name: '3'},
            {value: 5, name: '5'},
            {value: 10, name: '10'},
            {value: 25, name: '25'},
            {value: 'custom', name: 'Custom'},
    ];
```

Your translate function on the $rootScope works, but when I turn debugging on, translation can't be found for the numbers.
I tried doing the following instead:
```
vm.quantityOptions = [
            {value: 1, name: '1'},
            {value: 2, name: '2'},
            {value: 3, name: '3'},
            {value: 5, name: '5'},
            {value: 10, name: '10'},
            {value: 25, name: '25'},
            {value: 'custom', name: gettextCatalog.getString('Custom')},
        ];
```
But that doesn't work for me when lazy loading languages.

Any suggestions?

Thanks,

Michael
