### ISSUE TITLE
sprintf support

### ISSUE THREAD

**Issue by gunta** [rubenv/angular-gettext#65]
Hi!

I see a need for having **sprintf** support inside `angular-gettext`.
Something like in [lingua](https://github.com/ErikAndreas/lingua) or [node-gettext-sprintf](https://github.com/Mindflash/node-gettext-sprintf).

Syntax would be like:

``` javascript
gettext("1 string, 1 int place-holder: %s, %d", "test-string", 30)
```

or

``` javascript
gettext("Skipping duplicate, %1$s %2$s is already in the list", [ar,al] )
```

This is needed because interpolating angular `{{variables}}` is usually a bad idea, the variable names may change, and that would require a re-translation making the strings too volatile.

Thank you!

**Comment by YonathanB** [comment]
@rubenv , your solution is to insert the string in the html code, but I need it in the JS.
Is there a solution?

**Comment by rubenv** [comment]
Yes, there's a whole section on strings-in-JS in the dev guide: https://angular-gettext.rocketeer.be/dev-guide/annotate-js/

Just chain that:
```
{{ myVar | translate | sprintf:3 }}
```
