### ISSUE TITLE
Translation strings inside constants?

### ISSUE THREAD

**Issue by rfgamaral** [rubenv/angular-gettext#67]
I've created this issue but I have a feeling I'll be out of luck, which will prevent our team from using this system for internationalization. Which sucks because it's awesome and has many advantages over other translations systems.

The thing is, every piece of dynamic text is not defined in factories, services, controllers or whatever, but in constants. We have the app split by modules and each module has it's own constant file. The strings for that module are defined there, along with specific module configuration constants.

But constants don't allow DI so we can't inject either `gettextCatalog` or `gettext`. This presents a huge problem for us... We will either discard `angular-gettext` and use a completely different tool or we have to do a major refactor to our architectural structure.

Or... Is there a third solution that could help us solve this problem with little changes/refactor?

**Comment by shaurabh-singh** [comment]
Hi,
how did you manage to use the globally declared gettext method inside the constant file to tag strings for translation. I am not able to get how actually we can tag strings in constants for extraction.

**Comment by mpiasta-ca** [comment]
@shaurabh-singh, like so:

```
app.constant('ModalContent', {
  'ConnectionFailed': {
    title: gettext('Connection Failed'),
    body: gettext('Unable to resolve connection to the server. Please try again.');
});

function gettext (string) { 
  return string; 
}
```

And then your controller can consume the constant, send it to the view to display, and then you just slap a `translate` filter around your output variable.

```
app.controller('MyController', function ($scope, ModalContent) {
  $scope.error = ModalContent['ConnectionFailed'];
});
```

...and your view:

```
<div ng-controller="MyController">
  <h1 class="title" ng-if="error.title">{{error.title | translate}}</h1>
  <p class="body" ng-if="error.body">{{error.body | translate}}</p>
</div>
```
