### ISSUE TITLE
ISO 639 (language) and ISO 3166-1 alpha-2 (2-letter country) codes.

### ISSUE THREAD

**Issue by intellix** [rubenv/angular-gettext#69]
Was looking at using the Plural functionality within this library and noticed that here: https://github.com/rubenv/angular-gettext/blob/master/src/plural.js#L4 It requires a 2 character `language` rather than `locale` in the typical format of `en-GB, sv-SE` etc.

If I want to have an app localised for both British and American then there's nothing I can do. 

I think angular-gettext storing locale adds extra flexibility. The language can still be extracted as the first 2 characters if you want that.

**Comment by rubenv** [comment]
We now support this, though you'll need to use the gettext-standard underscore: `en_GB`.
