### ISSUE TITLE
Performance and Bind/Translate-once

### ISSUE THREAD

**Issue by intellix** [rubenv/angular-gettext#80]
So with angular comes the magic that everything is two-way bound and things update automatically. When a user selects his language using angular-gettext, his strings are all magically changed, which is awesome.

Right now I'm looking at the performance and responsiveness of a tablet app I'm creating. With the Batarang performance tab I'm seeing that the following function accounts for 60% in `Watch Expressions`:

``` js
function () {
  var prev = clone.html();
  // Fetch correct translated string.
  var translated;
  if (attrs.translatePlural) {
    $scope = pluralScope || (pluralScope = $scope.$new());
    $scope.$count = countFn($scope);
    translated = gettextCatalog.getPlural($scope.$count, input, attrs.translatePlural);
  } else {
    translated = gettextCatalog.getString(input);
  }
  // Interpolate with scope.
  var interpolated = $interpolate(translated)($scope);
  if (prev === interpolated) {
    return;  // Skip DOM change.
  }
  clone.html(interpolated);
  if (attrs.translateCompile !== undefined) {
    $compile(clone.contents())($scope);
  }
  return clone;
}
```

It's not a problem at all on desktop, it runs buttery smooth, but on tablet it's pretty sluggish. I can't get away with the amount of content that's on every page (I have a carousel with items that the user can slide through).

After seeing `Lazy one-time binding` support added to `Angular 1.3.0 beta 10` https://github.com/angular/angular.js/commit/cee429f0aaebf32ef1c9aedd8447a48f163dd0a4, I figured it would be awesome if we could bind-once for translating text.

A user isn't likely to change language often/ever so forever binding isn't that important and a page refresh wouldn't be an issue if they were wrongly assigned a locale upon entry.

I suppose there's nothing wrong with me adding bind-once to my translate filters like: `{{:: 'Hello' | translate}}` but wasn't sure how to tackle this when using the directive. 

What do you think?

**Comment by vecernik** [comment]
In version 2.3.8 extracting strings from {{:: 'Hello' | translate}} doesn't work (nor without spaces). Is there any config property to enabling that feature?
