### ISSUE TITLE
Duplicate translations

### ISSUE THREAD

**Issue by manuelmazzuola** [rubenv/angular-gettext#98]
With the last version v1.1.0 gettext duplicates translations.

```
<a translate>Sign up</a>
```

is translated to

```
<a translate>Sign upSign up</a>
```

**Comment by carlosgalindo** [comment]
Please see my comment @ https://github.com/rubenv/angular-gettext/issues/161#issuecomment-87016083

**Comment by circlingthesun** [comment]
Could those of you experiencing this issue check if #187 resolves it?
